### ISSUE TITLE
Is this plugin tested?

### ISSUE THREAD

**Issue by krutoo** [kirwako/strapi-plugin-media-prefix#1]
Hi, this plugin is exactly what i need, but it is not working with no reason.

Is it tested on clean strapi project?

**Comment by kirwako** [comment]
Can you share the test project or create a GitHub repository with your code so we can debug it together?
because the plugin is tested well and I am working with it in my projects

**Comment by kirwako** [comment]
1. did you enable the extention
```ts
// ./config/plugins.ts
export default () => ({
  "media-prefix": {
    enabled: true,
  },
});

```
2. did you add the key `MEDIA_PREFIX` with the website URL in `.env` file
```bash
#.env
MEDIA_PREFIX=https://kirwako.com/media
```
3. or did you add `PUBLIC_URL` in the `./config/server.ts` file like:
```ts
// ./config/server.ts
export default ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  app: {
    keys: env.array('APP_KEYS'),
  },
  url: env('PUBLIC_URL', 'http://localhost:1337'), // be sure to add this line
});

```

**Comment by kirwako** [comment]
I made a tutorial for you to explain how to set up the plugin with ease.
https://www.loom.com/share/63bbdb0a7f934b8ab5f920318f4b3d03?sid=92772cbf-ded0-4b9d-bb09-ce4752859900

**Comment by krutoo** [comment]
@kirwako I tried 1 ,2 and 3 steps from your answer but it is not working.

I also noticed that this plugin gets data not from `.env` (as written in readme) file but from `process.env` (this is not same things)

Im in process of creating reporduction example

**Comment by krutoo** [comment]
@kirwako Hmm, looks like it now works with no reason...

**Comment by kirwako** [comment]
you access to variables from `.env` file by `process.env`

**Comment by krutoo** [comment]
> you access to variables from `.env` file by `process.env`

@kirwako process.env contains variables not only from .env files but also from environment of runtime

**Comment by kirwako** [comment]
yes agree, but this is the only way to access to `.env` file variables

**Comment by krutoo** [comment]
> yes agree, but this is the only way to access to `.env` file variables

No, you can just read this file for example by dotenv or fs readfile

**Comment by kirwako** [comment]
in this case, you will add another package dotenv.
It's better to use tools and things provided by Strapi.

**Comment by krutoo** [comment]
@kirwako i understand i just want to say that this plugin do not uses `.env` file directly, it uses environment variables from `process.env`, which could get there not only from `.env` files, you can check this simply by running Strapi in an environment where the target variable is already set (and not set in file)

**Comment by kirwako** [comment]
agree with you @krutoo
